language: c

jobs:
  include:
    - os: linux
      dist: bionic
      install:
        - sudo pip install pytest
    - os: osx
      osx_image: xcode10.2  # nasty hack to get Python 3 (see https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci)
      install:
        - sudo pip install pytest
    - os: windows

# <! --- big and mostly copy-pasted block from https://docs.travis-ci.com/user/reference/windows/
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain

        # PCHIU: install compilers and libs
        $msys2 pacman -Sy mingw-w64-x86_84-gcc-fortran mingw-w64-x86_64-lapack
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it

        # PCHIU: install Python3
        choco install python3 --version=3.7.3
        export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

# end copy-pasted block --!>

addons:
  apt:
    - gfortran
    - libblas-dev
    - libopenblas-dev
  homebrew:
    casks:
      - gfortran
    packages:
      - openblas
      - lapack

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then $mingw64 printenv; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then $mingw64 cmake -G "Unix Makefiles" -DOPENMP=OFF ../ && make install; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cmake -DOPENMP=OFF ../ && make install; fi
  - cd ..
  - bin/cactus
  - cd test/RegTest
  - PATH=$PATH:../../bin/ pytest runreg.py
